name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
   
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Format Check
        run: deno fmt --check

      - name: Build
        run: deno task build

      - name: Deploy
        run: echo "$CLASPRC" > ~/.clasprc.json && deno task build deploy
        env:
          CLASPRC: ${{ secrets.CLASPRC }}
       