name: Build

on: [push, pull_request]

jobs:
  check:
    runs-on: ubuntu-latest
    env:
      DENO_DIR: my_cache_directory
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Cache Deno dependencies
        uses: actions/cache@v2
        with:
          path: ${{ env.DENO_DIR }}
          key: ${{ hashFiles('deno.lock') }}

      - name: Format Check
        run: deno fmt --check

      - name: Lint
        run: deno lint

      - name: Test
        run: deno test --allow-read --allow-write --allow-env --allow-net --allow-run
  build:
    runs-on: ubuntu-latest
    needs: check
    env:
      DENO_DIR: my_cache_directory
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Cache Deno dependencies
        uses: actions/cache@v2
        with:
          path: ${{ env.DENO_DIR }}
          key: ${{ hashFiles('deno.lock') }}
    
      - name: "Create env file"
        run: |
          echo "${{ secrets.INTERACTIVE_BROKERS_FLEX_WEB_TOKEN }}" > .env
  
      - name: Build
        run: deno task build

      - name: Deploy
        run: echo "$CLASPRC" > ~/.clasprc.json && deno task deploy
        env:
          CLASPRC: ${{ secrets.CLASPRC }}
